### ISSUE TITLE
Support multiple return values

### ISSUE THREAD

**Issue by minchingtonak** [basilTeam/basil#10]
Support for functions returning multiple values has many implications in terms of potential language features:

- Being able to index intro lists using lists (`list[1 .. 5]`, where `..` returns the range from 1 to 5)
- Comprehensions

**Comment by dumblob** [comment]
- Optionals ([in V](https://github.com/vlang/v/blob/master/doc/docs.md#optionresult-types-and-error-handling ), [in Rust](https://doc.rust-lang.org/std/option/ ), etc.)

**Comment by elucent** [comment]
Tentatively closing, as this behavior is largely covered by the new tuple types. We can probably reopen discussion for something like a splat operator at a later date.

**Comment by dumblob** [comment]
I think splat operator could be "easily faked" with macros and a compile-time list or key-value map. So I think it's very low priority.
