### ISSUE TITLE
Bug in allowing elided ':' in infix operator/macro calls

### ISSUE THREAD

**Issue by minchingtonak** [basilTeam/basil#13]
```
infix (x added-to y :and z)
    x + y + z

display (1 added-to 2 and 3)
```

Expected output: 
```
6
```

Actual output:
```
Expected term in binary expression.
Expected term in binary expression.
Could not evaluate term 'error'.
```

However, the above code will run correctly if the call to `added-to` includes a quoted `and`:
```
display (1 added-to 2 :and 3)
```

**Comment by elucent** [comment]
Closing, since this syntax is pretty obsolete by this point. The following code compiles just fine in the current v1.0 branch:
![image](https://user-images.githubusercontent.com/9532786/135808804-6bc2bd16-2c0f-4a87-8e1e-d34524f05df6.png)
