### ISSUE TITLE
AsmJit C++ library for easy and super-fast compilation to ASM

### ISSUE THREAD

**Issue by dumblob** [basilTeam/basil#14]
I've heard that Basil might want to generate its own assembly to allow for some tricks not applicable to other languages.

For that purpose I'd propose a library which I myself consider as the best from state-of-the-art libraries dealing with ASM on the highest possible level (including semi-automated register allocation/deallocation etc.).

https://asmjit.com/

**Comment by dumblob** [comment]
Interesting, AsmJIT is now being used even by [Erlang](https://blog.erlang.org/the-road-to-the-jit/ ) and other huge need-to-be-reliable projects (e.g. Facebook uses it) :open_mouth:.

It can be used also for code generation (instead of JITing) without the need to go much into those many differences among platforms (this allows [Blend2D](https://blend2d.com/performance.html ) to be significantly faster than Cairo/Qt/... by a huge margin).

**Comment by dumblob** [comment]
And if you decided to use e.g. LLVM (IR) instead, then I'd recommend taking a similar approach as [LLVM crap](https://github.com/c3d/xl/blob/master/src/llvm-crap.cpp ) (or even using it) to avoid the pain of an ever-changing API which LLVM does too often :cry:.

**Comment by elucent** [comment]
Basil is rolling its own backend, although an LLVM backend in addition to the Jasmine/native backend is potentially worth exploring. Closing for now - we'll open a separate issue if we add LLVM support. As it stands it's just too bulky of a dependency, and it'd be nice if we could get better compile times while we're at it.

**Comment by dumblob** [comment]
You mentioned LLVM backend, but what about AsmJit (which is what this thread is primarily about)?

**Comment by elucent** [comment]
I don't see much unique value in it. Basil has had its own independent x86_64 assembler since the language jam (in `jasmine/x64.cpp`). I've been testing it more rigorously lately and it seems to hold up pretty well. AsmJit would potentially be a bit more stable, but it would also require an external dependency, and Basil's Jasmine assembler has a number of unique properties that make it desirable - we have an OS-independent object file format, for example, that can also be used to store portable Jasmine bytecode.

**Comment by dumblob** [comment]
>I've been testing it more rigorously lately and it seems to hold up pretty well.

In this light AsmJit would bring only one thing - support for other architectures (especially ARM).

But I think I understand why jasmine is a better fit so far :wink:

**Comment by elucent** [comment]
AsmJit looks like it only barely supports ARM? I feel reasonably confident we could implement ARM (or other archs) support in Jasmine relatively easily, at least for whatever subset of instructions Basil needs.

**Comment by dumblob** [comment]
ARM support is still mainly downstream due to more testing needed, but it exists and is full-featured (disclaimer: I know the guy a bit).
