### ISSUE TITLE
Unable to lex escaped backslash in string literal

### ISSUE THREAD

**Issue by minchingtonak** [basilTeam/basil#17]
Datum:
```
"\\"
```

Expected lex:
```
"\"
```

Actual lex:
```
[1:5] Expected closing quote in string literal.
```

**Comment by elucent** [comment]
Same thing as #16: works just fine in the rewritten lexer/parser. :) 
![image](https://user-images.githubusercontent.com/9532786/135810135-0db329de-70bc-4a55-bc32-866fd30b2f76.png)
