### ISSUE TITLE
XL lang with some similarities to Basil

### ISSUE THREAD

**Issue by dumblob** [basilTeam/basil#24]
I've just come across [XL](https://github.com/c3d/xl ) and am quite surprised by its capabilities and simplicity. It's default compiler is written in C++ and it can compile to native binary as well as to bytecode (for which there is a VM).

XL seems a bit similar to Basil when it comes to the goals, so it might be a good source of inspiration. XL is being actively developed, so there is also plenty of room to influence XL itself :wink:.

**Comment by elucent** [comment]
It does look pretty interesting, I hadn't heard of it before. I'll keep an eye out.
